language: cpp
sudo: required

env:
  matrix:
    - "BUILD_TYPE=Release"
    - "BUILD_TYPE=Debug"

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev qt5-default qttools5-dev-tools qtmultimedia5-dev

script:
  - mkdir Build_${BUILD_TYPE}
  - cd Build_${BUILD_TYPE}
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLRCX_ENABLE_TESTS=1
  - make -j
  - bin/test_player
  - bin/test_reader
